package model

type Properties_1_20_15_01 struct {
	ServerName                             string  `properties:"server-name"`
	GameMode                               string  `properties:"gamemode"`
	ForceGameMode                          bool    `properties:"force-gamemode"`
	Difficulty                             string  `properties:"difficulty"`
	AllowCheats                            bool    `properties:"allow-cheats"`
	MaxPlayers                             int     `properties:"max-players"`
	OnlineMode                             bool    `properties:"online-mode"`
	AllowList                              bool    `properties:"allow-list"`
	ServerPort                             int     `properties:"server-port"`
	ServerPortV6                           int     `properties:"server-portv6"`
	EnableLanVisibility                    bool    `properties:"enable-lan-visibility"`
	ViewDistance                           int     `properties:"view-distance"`
	TickDistance                           int     `properties:"tick-distance"`
	PlayerIdleTimeout                      int     `properties:"player-idle-timeout"`
	MaxThreads                             int     `properties:"max-threads"`
	LevelName                              string  `properties:"level-name"`
	LevelSeed                              string  `properties:"level-seed"`
	DefaultPlayerPermissionLevel           string  `properties:"default-player-permission-level"`
	TexturePackRequired                    bool    `properties:"texturepack-required"`
	ContentLogFileEnabled                  bool    `properties:"content-log-file-enabled"`
	CompressionThreshold                   int     `properties:"compression-threshold"`
	CompressionAlgorithm                   string  `properties:"compression-algorithm"`
	ServerAuthoritativeMovement            string  `properties:"server-authoritative-movement"`
	PlayerMovementScoreThreshold           int     `properties:"player-movement-score-threshold"`
	PlayerMovementActionDirectionThreshold float64 `properties:"player-movement-action-direction-threshold"`
	PlayerMovementDistanceThreshold        float64 `properties:"player-movement-distance-threshold"`
	PlayerMovementDurationThresholdInMs    int     `properties:"player-movement-duration-threshold-in-ms"`
	CorrectPlayerMovement                  bool    `properties:"correct-player-movement"`
	ServerAuthoritativeBlockBreaking       bool    `properties:"server-authoritative-block-breaking"`
	ChatRestriction                        string  `properties:"chat-restriction"`
	DisablePlayerInteraction               bool    `properties:"disable-player-interaction"`
	ClientSideChunkGenerationEnabled       bool    `properties:"client-side-chunk-generation-enabled"`
	BlockNetworkIdsAreHashes               bool    `properties:"block-network-ids-are-hashes"`
	DisablePersona                         bool    `properties:"disable-persona"`
	DisableCustomSkins                     bool    `properties:"disable-custom-skins"`
	ServerBuildRadiusRatio                 string  `properties:"server-build-radius-ratio"`
}

type Properties_1_20_62_02 struct {
	ServerName                                      string  `properties:"server-name"`
	GameMode                                        string  `properties:"gamemode"`
	ForceGameMode                                   bool    `properties:"force-gamemode"`
	Difficulty                                      string  `properties:"difficulty"`
	AllowCheats                                     bool    `properties:"allow-cheats"`
	MaxPlayers                                      int     `properties:"max-players"`
	OnlineMode                                      bool    `properties:"online-mode"`
	AllowList                                       bool    `properties:"allow-list"`
	ServerPort                                      int     `properties:"server-port"`
	ServerPortV6                                    int     `properties:"server-portv6"`
	EnableLanVisibility                             bool    `properties:"enable-lan-visibility"`
	ViewDistance                                    int     `properties:"view-distance"`
	TickDistance                                    int     `properties:"tick-distance"`
	PlayerIdleTimeout                               int     `properties:"player-idle-timeout"`
	MaxThreads                                      int     `properties:"max-threads"`
	LevelName                                       string  `properties:"level-name"`
	LevelSeed                                       string  `properties:"level-seed"`
	DefaultPlayerPermissionLevel                    string  `properties:"default-player-permission-level"`
	TexturePackRequired                             bool    `properties:"texturepack-required"`
	ContentLogFileEnabled                           bool    `properties:"content-log-file-enabled"`
	CompressionThreshold                            int     `properties:"compression-threshold"`
	CompressionAlgorithm                            string  `properties:"compression-algorithm"`
	ServerAuthoritativeMovement                     string  `properties:"server-authoritative-movement"`
	PlayerPositionAcceptanceThreshold               float64 `properties:"player-position-acceptance-threshold"`
	PlayerMovementActionDirectionThreshold          float64 `properties:"player-movement-action-direction-threshold"`
	PlayerMovementDistanceThreshold                 float64 `properties:"player-movement-distance-threshold"`
	PlayerMovementDurationThresholdInMs             int     `properties:"player-movement-duration-threshold-in-ms"`
	CorrectPlayerMovement                           bool    `properties:"correct-player-movement"`
	ServerAuthoritativeBlockBreaking                bool    `properties:"server-authoritative-block-breaking"`
	ServerAuthoritativeBlockBreakingPickRangeScalar float64 `properties:"server-authoritative-block-breaking-pick-range-scalar"`
	ChatRestriction                                 string  `properties:"chat-restriction"`
	DisablePlayerInteraction                        bool    `properties:"disable-player-interaction"`
	ClientSideChunkGenerationEnabled                bool    `properties:"client-side-chunk-generation-enabled"`
	BlockNetworkIdsAreHashes                        bool    `properties:"block-network-ids-are-hashes"`
	DisablePersona                                  bool    `properties:"disable-persona"`
	DisableCustomSkins                              bool    `properties:"disable-custom-skins"`
	ServerBuildRadiusRatio                          string  `properties:"server-build-radius-ratio"`
	AllowOutboundScriptDebugging                    bool    `properties:"allow-outbound-script-debugging"`
	AllowInboundScriptDebugging                     bool    `properties:"allow-inbound-script-debugging"`
	ScriptDebuggerAutoAttach                        string  `properties:"script-debugger-auto-attach"`
}
